### PR TITLE
Refresh design of root page

### PR DESCRIPTION
**Pull request by antw**
* Refreshes the design to highlight the ETM first.
* Games appear below, with a section of their own.
* Added "About Us" to describe Quintel.
* Upgraded Bootstrap to v4
* Removed old JS and CSS files.

Following feedback by @jorisberkhout on Basecamp, the main ETM image is larger and oblique when in a large browser, and reduces to a smaller size when the browser is narrowed.

We require a translation for the "About Us" section on the root page. This was copy/pasted from the quintel.com site, but that only has text in English. https://github.com/quintel/etcentral/blob/558662c7f0e65b44bd3cfb911f631d690e1618db/config/locales/nl_landing_page.yml#L8-L16

I've tested in

* macOS: Chrome, Firefox, Safari
* Windows 10: Internet Explorer 10
* iOS: Safari

screencapture-localhost-3003-2020-08-18-13_21_34

### CODE REVIEW

**Comment by noracato** [comment]
Really like it!

The  _superhero_ ETM and the removal of the ocean (still can't get over that one 😄 ) are great improvements. It's looking so much nicer than etcentral does now.

I also looked at the other pages you refreshed. I liked what you did to the contact page, making it shorter. However, I feel the new compact font you chose (nice pick!) makes the partner page feel a little more crammed than it used to be. Not that it could _not_ feel crammed with all the logos. Just adding some space under the headers would be sufficient imo, but if you don't think that's neccessary, I'm fine with that as well.

Screenshot 2020-08-18 at 17 00 07

Again, nice! 🎉

**Comment by antw** [comment]
> Not that it could not feel crammed with all the logos. Just adding some space under the headers would be sufficient imo, but if you don't think that's neccessary, I'm fine with that as well.

Agreed, good catch. I've adjusted the header margins on that page and stacked the categories rather than putting them in columns. I think this looks better: it's less cluttered and the partners who provide the greatest support are now all shown at the top of the page, rather than being somewhere in the long left column.

Screenshot 2020-08-18 at 16 39 07

**Comment by MartLubben** [comment]
Hi Anthony,

I am impressed! My first reaction while seeing this was a loud 'Wow'. 
I really like that my eyes are drawn to the hourly curves.

**Review by MartLubben — APPROVED** [review]

**Comment by ChaelKruip** [comment]
Really nice work!

**Review by noracato — APPROVED** [review]

**Comment by antw** [comment]
> We require a translation for the "About Us" section on the root page. This was copy/pasted from the quintel.com site, but that only has text in English. https://github.com/quintel/etcentral/blob/558662c7f0e65b44bd3cfb911f631d690e1618db/config/locales/nl_landing_page.yml#L8-L16

@MartLubben @noracato: Would one of you mind doing this translation when you have a spare couple of minutes? Please and thank you.

**Pull request merged**
