### PR TITLE
Added ETmoses on front page + clean up

### PR DESCRIPTION
**Pull request by dennisschoenmakers**
image

### CODE REVIEW

**Comment by dennisschoenmakers** [comment]
Assigned @ChaelKruip. Merge if pleased.

**Comment by ChaelKruip** [comment]
As discussed with @dennisschoenmakers an alternative image with fewer load points will be considered.

**Comment by jorisberkhout** [comment]
Looks very good! If I can have one suggestion, I would change *kwartierniveau* to *kwartierbasis*.

**Comment by dennisschoenmakers** [comment]
After ac2b656fa429ff4c91a8e6101985b472d0bed5ec

image

**Comment by ChaelKruip** [comment]
:+1:

**Pull request merged**
