### PR TITLE
Add redirects to RLI scenarios to config/routes.rb

### LINKED ISSUE #122: RLI scenarios should be redirected to beta now, later to production
The following links should redirect currently to the next beta scenarios:

1. http://energietransitiemodel.nl/ser-scenario-2023 => http://beta.pro.et-model.com/scenarios/193349
2. http://energietransitiemodel.nl/80%-co2-reductiescenario-2050 => http://beta.pro.et-model.com/scenarios/423879
3. http://energietransitiemodel.nl/95%-co2-reductiescenario-2050 => http://beta.pro.et-model.com/scenarios/423882

I guess we can simply use:

```ruby
match "/name" => redirect {"http://beta.pro.et-model.com/scenarios/blah"}
```

in `config/routes.rb`

As requested by @AlexanderWirtz. 

Assigning @twilkinson573. Please put this in a Pull Request, including @jorisberkhout due to the deployment restrictions.

### PR DESCRIPTION
**Pull request by twilkinson573**
Adds three descriptive URLs to link straight to ET Model beta scenarios. Specs passing. Closes #122 

cc @dennisschoenmakers @AlexanderWirtz

### CODE REVIEW

**Comment by jorisberkhout** [comment]
Nice work, @twilkinson573 . I have validated that the links indeed refer to the desired scenarios. Assigning @dennisschoenmakers to check the technical side of this pull request.

**Comment by dennisschoenmakers** [comment]
@twilkinson573 : can you also add specs for these redirects? They are rather (read: 'extremely') important :smile:

**Comment by twilkinson573** [comment]
The links are now: 

[http://energietransitiemodel.nl/rli/ser-scenario-2023]()
[http://energietransitiemodel.nl/rli/80-procent-co2-reductiescenario-2050]()
[http://energietransitiemodel.nl/rli/95-procent-co2-reductiescenario-2050]()

Working locally and specs passing.

**Comment by dennisschoenmakers** [comment]
:+1: excellent.

**Comment by dennisschoenmakers** [comment]
Deploying to staging now. @jorisberkhout could you test this extensively? I suggest we proceed to deploy this to **live** as well.

**Comment by dennisschoenmakers** [comment]
It has been deployed to **live**!

**Comment by twilkinson573** [comment]
All three seem to work fine when I test them! :relieved:

**Comment by jorisberkhout** [comment]
Same here! Good job guys!

**Comment by AlexanderWirtz** [comment]
Works like a charm! Good busy everyone!

**Pull request merged**
